comment:
  layout: "header, diff, flags, components"

component_management:
  individual_components:
    - component_id: hardcover_list
      name: hardcover-list
      paths:
        - src/**
        - lib/**
